Repository Qld-Health-Online-Team/design-system, pull requests merged in 2024-01, with the labels that each got.

#80 Fix/fixing quote dept 171
  src/components/_global/css/body/component.scss
Labels: bug

#77 Fix/lists mark qhwt 876
  src/components/_global/css/body/component.scss
  src/html/component-global-elements.html
Labels: minor

#82 Fixing the spacings - QHWT-876
  src/components/_global/css/body/component.scss
Labels: minor

#99 Release v1.3.2
  dist/component-basic_search.html
  dist/components/_global/import.xml
  dist/components/_template/import.xml
  dist/components/a-z_listing/import.xml
  dist/components/abstract/import.xml
  dist/components/accordion/import.xml
  dist/components/banner/import.xml
  dist/components/banner_advanced/import.xml
  dist/components/banner_basic/import.xml
  dist/components/banner_intermediate/import.xml
  dist/components/basic_search/import.xml
  dist/components/basic_search/presentation.js
  dist/components/body/import.xml
  dist/components/breadcrumbs/import.xml
  dist/components/callout/import.xml
  dist/components/card_feature/import.xml
  dist/components/card_multi_action/import.xml
  dist/components/card_no_action/import.xml
  dist/components/card_single_action/import.xml
  dist/components/code/import.xml
  dist/components/data_table/import.xml
  dist/components/footer/import.xml
  dist/components/global_alert/import.xml
  dist/components/header/import.xml
  dist/components/horizontal_rule/import.xml
  dist/components/in_page_navigation/import.xml
  dist/components/internal_navigation/import.xml
  dist/components/left_hand_navigation/import.xml
  dist/components/main_navigation/import.xml
  dist/components/mega_main_navigation/import.xml
  dist/components/multi_column/import.xml
  dist/components/page_alert/import.xml
  dist/components/pagination/import.xml
  dist/components/tab/import.xml
  dist/components/updated_date/import.xml
  dist/components/widgets/import.xml
  dist/main.css
  dist/main.css.map
  package-lock.json
  src/components/basic_search/css/component.scss
  src/components/basic_search/html/component.hbs
Labels: patch
